name: deploy

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  install:
    name: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node 17
        uses: actions/setup-node@v2
        with:
          node-version: 17.0.1

      - name: install dependencies
        run: npm ci

  build:
    name: build
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2

      - name: build site
        run: npm run build-all

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages