name: deploy

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: build site
        run: npm run build-all

      - name: Commit changes
        run: |
          git config --global user.name 'Nikita Rusetskii'
          git config --global user.email 'xtenzq@users.noreply.github.com'
          git commit -am 'Updates files'
          git push

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages